# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Rebase pt-nightly-compatible
on:
  schedule:
    # Note that cron uses UTC times and weeks start from Sunday (0).
    # We rebase pt-nightly-compatible every month.
    - cron:  '0 13 20 * *'

  workflow_dispatch:

jobs:
  update-n-send-PR:
    if: github.repository == 'awslabs/ratex'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Rebase onto main branch
        run: |
          git fetch --all
          git checkout -b pt-nightly-compatible origin/pt-nightly-compatible
          git rebase main pt-nightly-compatible
      - name: Create timestamp
        id: date
        run: echo "::set-output name=now::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: '[Compatible] Rebase PyTorch Nightly Compatible ${{ steps.date.outputs.now }}'
          committer: GitHub <noreply@github.com>
          author: AIREMetaBot <aire-meta-bot@users.noreply.github.com>
          branch: rebase-pytorch-nightly-compatible-${{ steps.date.outputs.now }}
          base: pt-nightly-compatible
          delete-branch: true
          title: '[Compatible] Rebase PyTorch Nightly Compatible ${{ steps.date.outputs.now }}'
          body: |
            _This PR is auto-generated by AIRE Meta Bot._
            
            - Please check the CI results before merge it.
            - Please use rebase merge to keep pt-nightly-compatible branch against the main branch.
            - If one or more tests failed, please commit necessary changes to this branch (rebase-pytorch-nightly-compatible-${{ steps.date.outputs.now }}).
          draft: false
